### PR TITLE
Update adapters.rst

### PR DESCRIPTION
**Pull request by mrshu**
* Fix small typo in `create_engine`

### CODE REVIEW

**Comment by betodealmeida** [comment]
Thanks!

**Comment by betodealmeida** [comment]
@mrshu wold you mind adding your name to https://github.com/betodealmeida/shillelagh/blob/main/AUTHORS.rst also?

**Comment by mrshu** [comment]
@betodealmeida sure thing!

Sorry about those failing tests though -- I am not really sure what to do about those in here

**Comment by betodealmeida** [comment]
> Sorry about those failing tests though -- I am not really sure what to do about those in here

Oh, no worries. The integration test is failing because you don't have access to the credentials needed to run them (otherwise someone could make a PR that leaks those credentials), I'll mark it as not-required. The coverage test is a bit aggressive, I've had problems with it in the past, I might just get rid of it, since the build tests also check coverage.

**Comment by mrshu** [comment]
Cool! 

Thanks a bunch for both resolving that and for Shillelagh as well -- it has been a very nice fit for a niche need I had for quite a bit. Here is to hoping the Superset API will be supported in the future as well -- things like https://github.com/slidoapp/dbt-superset-lineage will end up being much cleaner in the process :slightly_smiling_face:

**Comment by betodealmeida** [comment]
> Cool!
> 
> Thanks a bunch for both resolving that and for Shillelagh as well -- it has been a very nice fit for a niche need I had for quite a bit. Here is to hoping the Superset API will be supported in the future as well -- things like https://github.com/slidoapp/dbt-superset-lineage will end up being much cleaner in the process 🙂

You're welcome! Thank you for `dbt-superset-lineage`, I've been exploring ways of integrating DBT and Superset better and it was super helpful!

**Pull request merged**
