### PR TITLE
chore: remove duplicate requests deps and bump ver

### PR DESCRIPTION
**Pull request by cwegener**
Set a new minimum requests version to avoid https://github.com/advisories/GHSA-j8r2-6x86-q33q

### CODE REVIEW

**Review by betodealmeida — APPROVED** [review]
Thanks!

**Comment by cancan101** [comment]
Just a double check, the tests are not failing due to the dependency change? The release notes indicated there's a small chance of breaking changes

**Comment by betodealmeida** [comment]
> Just a double check, the tests are not failing due to the dependency change? The release notes indicated there's a small chance of breaking changes

Thanks for checking! It was just the integration tests that failed, the GitHub secrets needed are not available to non-contributors so they always fail.

**Comment by betodealmeida** [comment]
They ran after I merged and passed: https://github.com/betodealmeida/shillelagh/actions/runs/5085815926

**Pull request merged**
